services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: tripsocial
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tripsocial_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: tripsocial_app
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - "8080:8080"
      - "5005:5005" # Porta para Debug no Editor/IDE
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tripsocial_db

volumes:
  pgdata:
