services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      POSTGRES_USER: tripsocial
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tripsocial_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
